### PR TITLE
bidirectional dshot

### PR DESCRIPTION
**Pull request by dakejahl**
continuation of https://github.com/PX4/PX4-Autopilot/pull/20749

### CODE REVIEW

**Comment by dakejahl** [comment]
this is working

**Comment by jgw365** [comment]
Have you tested it in an actual drone? And has the bug in PX4 #20749, which caused a lot of CRC errors, been solved?

**Comment by jgw365** [comment]
@dakejahl

**Comment by dakejahl** [comment]
@jgw365 yes I'll be making a PR into PX4 shortly

**Comment by jgw365** [comment]
> @jgw365 yes I'll be making a PR into PX4 shortly

thank you

> @jgw365 yes I'll be making a PR into PX4 shortly

thanks so much for your work

**Comment by jgw365** [comment]
Should you comment out this line of code: px4_arch_gpiowrite(GPIO_FMU_CH8, true);?

**Pull request closed without merging**
